language: android
dist: trusty
android:
  android {
    buildTypes {
      debug {
        testCoverageEnabled true
      }
    }
  }
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools
    - extra
    
    
    # The BuildTools version used by your project
    - build-tools-1.3.10

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-28
    - sys-img-armeabi-v7a-android-17

env:
  global:
    - API=28 # Android API level 25 by default
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  
# https://stackoverflow.com/questions/42731625/travis-ci-failed-because-cannot-accept-license-constrain-layout
# needed b/c travis doesn't accept licenses
install:
  # List and delete unnecessary components to free space
  - sdkmanager --list || true
  #- sdkmanager --uninstall "system-images;android-15;default;armeabi-v7a"
  #- sdkmanager --uninstall "system-images;android-16;default;armeabi-v7a"
  #- sdkmanager --uninstall "system-images;android-17;default;armeabi-v7a"
  #- sdkmanager --uninstall "system-images;android-18;default;armeabi-v7a"
  #- sdkmanager --uninstall "system-images;android-19;default;armeabi-v7a"
  #- sdkmanager --uninstall "system-images;android-21;default;armeabi-v7a"
  - sdkmanager --uninstall "extras;google;google_play_services"
  - sdkmanager --uninstall "extras;android;support"
  - sdkmanager --uninstall "platforms;android-10"
  - sdkmanager --uninstall "platforms;android-15"
  - sdkmanager --uninstall "platforms;android-16"
  - sdkmanager --uninstall "platforms;android-17"
  - sdkmanager --uninstall "platforms;android-18"
  - sdkmanager --uninstall "platforms;android-19"
  - sdkmanager --uninstall "platforms;android-20"
  - sdkmanager --uninstall "platforms;android-21"
  - sdkmanager --uninstall "build-tools;28.0.3"
  # Update sdk tools to latest version and install/update components
  - echo yes | sdkmanager "tools"
  - echo yes | sdkmanager "platforms;android-25" # Latest platform required by SDK tools
  - echo yes | sdkmanager "platforms;android-${API}" # Android platform required by emulator
  - echo yes | sdkmanager "extras;android;m2repository"
  - echo yes | sdkmanager "extras;google;m2repository"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
  # - echo yes | sdkmanager "$EMULATOR" # Install emulator system image
  - ./gradlew build jacocoTestReport assembleAndroidTest
  ./gradlew connectedCheck
cache:  
  bundler: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
  
  
